const ata = [
    { ata: '21', title: 'AIR CONDITIONING' },
    { ata: '22', title: 'AUTO FLIGHT' },
    { ata: '23', title: 'COMMUNICATIONS' },
    { ata: '24', title: 'ELECTRICAL POWER' },
    { ata: '25', title: 'EQUIPMENT/FURNISHINGS' },
    { ata: '26', title: 'FIRE PROTECTION' },
    { ata: '27', title: 'FLIGHT CONTROLS' },
    { ata: '28', title: 'FUEL' },
    { ata: '29', title: 'HYDRAULIC POWER' },
    { ata: '30', title: 'ICE AND RAIN PROTECTION' },
    { ata: '31', title: 'INDICATING/RECORDING SYSTEMS' },
    { ata: '32', title: 'LANDING GEAR' },
    { ata: '33', title: 'LIGHTS' },
    { ata: '34', title: 'NAVIGATION' },
    { ata: '35', title: 'OXYGEN' },
    { ata: '36', title: 'PNEUMATIC' },
    { ata: '38', title: 'WATER/WASTE' },
    { ata: '46', title: 'INFORMATION SYSTEMS' },
    { ata: '47', title: 'INERT GAS SYSTEM' },
    { ata: '49', title: 'AIRBORNE AUXILIARY POWER' },
    { ata: '51', title: 'STANDARD PRACTICES AND STRUCTURES' },
    { ata: '52', title: 'DOORS' },
    { ata: '53', title: 'FUSELAGE' },
    { ata: '54', title: 'NACELLES/PYLONS' },
    { ata: '55', title: 'STABILIZERS' },
    { ata: '56', title: 'WINDOWS' },
    { ata: '57', title: 'WINGS' },
    { ata: '70(CFMI)', title: 'STANDARD PRACTICES - ENGINE' },
    { ata: '70(CFMB)', title: 'STANDARD PRACTICES - ENGINE - GENERAL' },
    { ata: '70(IAE)', title: 'STANDARD PRACTICES - ENGINE - GENERAL' },
    { ata: '71(CFMI)', title: 'POWER PLANT' },
    { ata: '71(CFMB)', title: 'POWER PLANT - GENERAL' },
    { ata: '71(IAE)', title: 'POWER PLANT - GENERAL' },
    { ata: '72(CFMI)', title: 'ENGINE' },
    { ata: '72(CFMB)', title: 'ENGINE - GENERAL' },
    { ata: '72(IAE)', title: 'ENGINE - GENERAL' },
    { ata: '73(CFMI)', title: 'ENGINE FUEL AND CONTROL' },
    { ata: '73(CFMB)', title: 'ENGINE FUEL AND CONTROL - GENERAL' },
    { ata: '73(IAE)', title: 'ENGINE FUEL AND CONTROL - GENERAL' },
    { ata: '74(CFMI)', title: 'IGNITION' },
    { ata: '74(CFMB)', title: 'IGNITION - GENERAL' },
    { ata: '74(IAE)', title: 'IGNITION - GENERAL' },
    { ata: '75(CFMI)', title: 'AIR' },
    { ata: '75(CFMB)', title: 'AIR - GENERAL' },
    { ata: '75(IAE)', title: 'AIR - GENERAL' },
    { ata: '76(CFMI)', title: 'ENGINE CONTROLS' },
    { ata: '76(CFMB)', title: 'ENGINE CONTROLS - GENERAL' },
    { ata: '76(IAE)', title: 'ENGINE CONTROLS - GENERAL' },
    { ata: '77(CFMI)', title: 'ENGINE INDICATING' },
    { ata: '77(CFMB)', title: 'ENGINE INDICATING - GENERAL' },
    { ata: '77(IAE)', title: 'ENGINE INDICATING - GENERAL' },
    { ata: '78(CFMI)', title: 'EXHAUST' },
    { ata: '78(CFMB)', title: 'EXHAUST - GENERAL' },
    { ata: '78(IAE)', title: 'EXHAUST - GENERAL' },
    { ata: '79(CFMI)', title: 'OIL' },
    { ata: '79(CFMB)', title: 'OIL - GENERAL' },
    { ata: '79(IAE)', title: 'OIL - GENERAL' },
    { ata: '80(CFMI)', title: 'STARTING' },
    { ata: '80(CFMB)', title: 'STARTING - GENERAL' },
    { ata: '80(IAE)', title: 'STARTING - GENERAL' },
];
