exports.users = () => [
    {
        username: 'user1',
        password: 'user1',
    },
    {
        username: 'user2',
        password: 'user2',
    },
    {
        username: 'user3',
        password: 'user3',
    },
    {
        username: 'user4',
        password: 'user4',
    },
];

exports.courses = () => [
    { internalRef: 'A001', title: 'B737Cl (CFM56-3) Cat. B2', location: 'VArna, BG', students: 12 },
    { internalRef: 'A002', title: 'B737Cl (CFM56-3) Cat. B1.1', location: 'Luqa, MT', students: 24 },
    { internalRef: 'A003', title: 'B737Cl (CFM56-3) Cat. B1.1', location: 'Sofia, BG', students: 23 },
    { internalRef: 'A004', title: 'B737Cl (CFM56-3) Cat. B1.1', location: 'Sofia, BG', students: 23 },
    { internalRef: 'A005', title: 'B737NG (CFM56-7) Cat. B1.1', location: 'Budapest, HU', students: 14 },
    { internalRef: 'A006', title: 'B737NG (CFM56-7) Cat. B2', location: 'Budapest, HU', students: 22 },
    { internalRef: 'A007', title: 'B737NG (CFM56-7) Cat. B2', location: 'Sofia, BG', students: 16 },
    { internalRef: 'A008', title: 'B737Cl (CFM56-3) Cat. B1.1', location: 'Budapest, HU', students: 25 },
    { internalRef: 'A009', title: 'B737Cl (CFM56-3) Cat. B2', location: 'Sofia, BG', students: 9 },
    { internalRef: 'A010', title: 'B737Cl (CFM56-3) Cat. B2', location: 'VArna, BG', students: 15 },
];

exports.ata = () => [
    { ata: '21', title: 'AIR CONDITIONING' },
    { ata: '22', title: 'AUTO FLIGHT' },
    { ata: '23', title: 'COMMUNICATIONS' },
    { ata: '24', title: 'ELECTRICAL POWER' },
    { ata: '25', title: 'EQUIPMENT/FURNISHINGS' },
    { ata: '26', title: 'FIRE PROTECTION' },
    { ata: '27', title: 'FLIGHT CONTROLS' },
    { ata: '28', title: 'FUEL' },
    { ata: '29', title: 'HYDRAULIC POWER' },
    { ata: '30', title: 'ICE AND RAIN PROTECTION' },
    { ata: '31', title: 'INDICATING/RECORDING SYSTEMS' },
    { ata: '32', title: 'LANDING GEAR' },
    { ata: '33', title: 'LIGHTS' },
    { ata: '34', title: 'NAVIGATION' },
    { ata: '35', title: 'OXYGEN' },
    { ata: '36', title: 'PNEUMATIC' },
    { ata: '38', title: 'WATER/WASTE' },
    { ata: '46', title: 'INFORMATION SYSTEMS' },
    { ata: '47', title: 'INERT GAS SYSTEM' },
    { ata: '49', title: 'AIRBORNE AUXILIARY POWER' },
    { ata: '51', title: 'STANDARD PRACTICES AND STRUCTURES' },
    { ata: '52', title: 'DOORS' },
    { ata: '53', title: 'FUSELAGE' },
    { ata: '54', title: 'NACELLES/PYLONS' },
    { ata: '55', title: 'STABILIZERS' },
    { ata: '56', title: 'WINDOWS' },
    { ata: '57', title: 'WINGS' },
    { ata: '70(CFMI)', title: 'STANDARD PRACTICES - ENGINE' },
    { ata: '70(CFMB)', title: 'STANDARD PRACTICES - ENGINE' },
    { ata: '70(IAE)', title: 'STANDARD PRACTICES - ENGINE' },
    { ata: '71(CFMI)', title: 'POWER PLANT' },
    { ata: '71(CFMB)', title: 'POWER PLANT' },
    { ata: '71(IAE)', title: 'POWER PLANT' },
    { ata: '72(CFMI)', title: 'ENGINE' },
    { ata: '72(CFMB)', title: 'ENGINE' },
    { ata: '72(IAE)', title: 'ENGINE' },
    { ata: '73(CFMI)', title: 'ENGINE FUEL AND CONTROL' },
    { ata: '73(CFMB)', title: 'ENGINE FUEL AND CONTROL' },
    { ata: '73(IAE)', title: 'ENGINE FUEL AND CONTROL' },
    { ata: '74(CFMI)', title: 'IGNITION' },
    { ata: '74(CFMB)', title: 'IGNITION' },
    { ata: '74(IAE)', title: 'IGNITION' },
    { ata: '75(CFMI)', title: 'AIR' },
    { ata: '75(CFMB)', title: 'AIR' },
    { ata: '75(IAE)', title: 'AIR' },
    { ata: '76(CFMI)', title: 'ENGINE CONTROLS' },
    { ata: '76(CFMB)', title: 'ENGINE CONTROLS' },
    { ata: '76(IAE)', title: 'ENGINE CONTROLS' },
    { ata: '77(CFMI)', title: 'ENGINE INDICATING' },
    { ata: '77(CFMB)', title: 'ENGINE INDICATING' },
    { ata: '77(IAE)', title: 'ENGINE INDICATING' },
    { ata: '78(CFMI)', title: 'EXHAUST' },
    { ata: '78(CFMB)', title: 'EXHAUST' },
    { ata: '78(IAE)', title: 'EXHAUST' },
    { ata: '79(CFMI)', title: 'OIL' },
    { ata: '79(CFMB)', title: 'OIL' },
    { ata: '79(IAE)', title: 'OIL' },
    { ata: '80(CFMI)', title: 'STARTING' },
    { ata: '80(CFMB)', title: 'STARTING' },
    { ata: '80(IAE)', title: 'STARTING' },
];

exports.questions = (atas, users) => {
    return [
        {
            question: 'Reprehenderit nisi non aute occaecat Lorem nostrud est ullamco elit proident mollit dolore.',
            ansA: 'anim minim officia nulla',
            ansB: 'aute cupidatat ad in',
            ansC: 'nostrud quis elit ad',
            correctAns: 'ansA',
            level: 2,
            author: users[Math.floor(Math.random() * users.length)],
            ata: atas[Math.floor(Math.random() * atas.length)],
        },
        {
            question: 'Labore veniam pariatur excepteur reprehenderit ipsum deserunt exercitation deserunt cillum ea cillum id reprehenderit.',
            ansA: 'irure cupidatat fugiat ipsum',
            ansB: 'aliquip officia ex nisi',
            ansC: 'ipsum culpa aliquip ad',
            correctAns: 'ansC',
            level: 1,
            author: users[Math.floor(Math.random() * users.length)],
            ata: atas[Math.floor(Math.random() * atas.length)],
        },
        {
            question: 'Qui officia officia nisi ullamco ad cillum voluptate dolore dolore.',
            ansA: 'esse aliqua et pariatur',
            ansB: 'fugiat aute eiusmod magna',
            ansC: 'occaecat ad in do',
            correctAns: 'ansB',
            level: 2,
            author: users[Math.floor(Math.random() * users.length)],
            ata: atas[Math.floor(Math.random() * atas.length)],
        },
        {
            question: 'Laborum consequat ut cillum cupidatat.',
            ansA: 'sit reprehenderit deserunt tempor',
            ansB: 'ut nisi dolore Lorem',
            ansC: 'est nulla ea sunt',
            correctAns: 'ansC',
            level: 1,
            author: users[Math.floor(Math.random() * users.length)],
            ata: atas[Math.floor(Math.random() * atas.length)],
        },
        {
            question: 'Quis Lorem eiusmod minim sunt do officia enim eiusmod ex veniam fugiat reprehenderit excepteur ut.',
            ansA: 'fugiat ea nulla esse',
            ansB: 'quis reprehenderit qui Lorem',
            ansC: 'minim et sint magna',
            correctAns: 'ansA',
            level: 2,
            author: users[Math.floor(Math.random() * users.length)],
            ata: atas[Math.floor(Math.random() * atas.length)],
        },
        {
            question: 'Consequat labore veniam adipisicing magna qui qui ipsum aute officia.',
            ansA: 'et labore ullamco dolor',
            ansB: 'eu qui pariatur amet',
            ansC: 'ea laborum in id',
            correctAns: 'ansB',
            level: 1,
            author: users[Math.floor(Math.random() * users.length)],
            ata: atas[Math.floor(Math.random() * atas.length)],
        },
        {
            question: 'Enim eu laborum aute ad officia cillum dolor.',
            ansA: 'aliquip do dolore laborum',
            ansB: 'tempor do eiusmod cillum',
            ansC: 'veniam aliquip dolore adipisicing',
            correctAns: 'ansA',
            level: 2,
            author: users[Math.floor(Math.random() * users.length)],
            ata: atas[Math.floor(Math.random() * atas.length)],
        },
        {
            question: 'Ad excepteur cupidatat eu consequat reprehenderit nulla aute dolore do cupidatat.',
            ansA: 'aliqua reprehenderit consequat duis',
            ansB: 'non in sint eiusmod',
            ansC: 'reprehenderit fugiat magna tempor',
            correctAns: 'ansA',
            level: 1,
            author: users[Math.floor(Math.random() * users.length)],
            ata: atas[Math.floor(Math.random() * atas.length)],
        },
        {
            question: 'Voluptate ad enim magna mollit laboris officia cillum deserunt.',
            ansA: 'laboris irure mollit Lorem',
            ansB: 'irure aute eu qui',
            ansC: 'eiusmod dolor et exercitation',
            correctAns: 'ansC',
            level: 3,
            author: users[Math.floor(Math.random() * users.length)],
            ata: atas[Math.floor(Math.random() * atas.length)],
        },
        {
            question: 'Anim aliqua eiusmod magna incididunt velit id nisi.',
            ansA: 'aliquip dolore sit nostrud',
            ansB: 'nisi laborum nostrud officia',
            ansC: 'ullamco elit reprehenderit aute',
            correctAns: 'ansA',
            level: 1,
            author: users[Math.floor(Math.random() * users.length)],
            ata: atas[Math.floor(Math.random() * atas.length)],
        },
    ];
};

exports.comments = (questionId, author) => [
    {
        comment: 'Ea nisi incididunt sit aute mollit sint dolor voluptate amet do qui esse mollit reprehenderit.',
        questionId: questionId[Math.floor(Math.random() * questionId.length)],
        author: author[Math.floor(Math.random() * author.length)],
    },
    {
        comment: 'Fugiat aliquip est veniam consectetur adipisicing non Lorem enim do ullamco duis veniam.',
        questionId: questionId[Math.floor(Math.random() * questionId.length)],
        author: author[Math.floor(Math.random() * author.length)],
    },
    {
        comment: 'Magna minim pariatur tempor minim non.',
        questionId: questionId[Math.floor(Math.random() * questionId.length)],
        author: author[Math.floor(Math.random() * author.length)],
    },
    {
        comment: 'Sint et in tempor sit ex.',
        questionId: questionId[Math.floor(Math.random() * questionId.length)],
        author: author[Math.floor(Math.random() * author.length)],
    },
    {
        comment: 'Tempor cillum sit duis nulla est non ipsum dolore culpa enim ea non esse duis.',
        questionId: questionId[Math.floor(Math.random() * questionId.length)],
        author: author[Math.floor(Math.random() * author.length)],
    },
    {
        comment: 'Minim ullamco sunt labore nulla mollit mollit aliquip magna aliquip.',
        questionId: questionId[Math.floor(Math.random() * questionId.length)],
        author: author[Math.floor(Math.random() * author.length)],
    },
    {
        comment: 'Nulla deserunt dolor pariatur officia ut qui eiusmod pariatur veniam ut.',
        questionId: questionId[Math.floor(Math.random() * questionId.length)],
        author: author[Math.floor(Math.random() * author.length)],
    },
    {
        comment: 'Cillum Lorem ad consectetur aliqua qui incididunt magna ut aliqua occaecat ex velit.',
        questionId: questionId[Math.floor(Math.random() * questionId.length)],
        author: author[Math.floor(Math.random() * author.length)],
    },
    {
        comment: 'Ea ea duis nulla velit quis qui do minim Lorem eu ad elit.',
        questionId: questionId[Math.floor(Math.random() * questionId.length)],
        author: author[Math.floor(Math.random() * author.length)],
    },
    {
        comment: 'Ipsum ea aute fugiat minim ad.',
        questionId: questionId[Math.floor(Math.random() * questionId.length)],
        author: author[Math.floor(Math.random() * author.length)],
    },
];

exports.userDetails = (userId) => [
    {
        userId: userId[0],
        dateOfBirth: '2001-01-01',
        email: 'fu@abv.bg',
        fullName: 'Pesho Peshov',
        placeOfBirth: 'Sliven',
        role: 'User',
        avatar: 'https://img.favpng.com/6/10/5/dave-the-minion-minions-portable-network-graphics-clip-art-despicable-me-png-favpng-NBRu9WBvhqe8YLD89FambWyj6.jpg',
    },
    {
        userId: userId[1],
        dateOfBirth: '1990-03-08',
        email: 'bar@abv.bg',
        fullName: 'Stamat Stamatov',
        placeOfBirth: 'Burgas',
        role: 'Admin',
        avatar: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRc8xHSVHV7Nt6DFPxEnPr2YI3WmMZRCgdyiA&usqp=CAU',
    },
    {
        userId: userId[2],
        dateOfBirth: '1995-09-08',
        email: 'gg@abv.bg',
        fullName: 'Gosho Goshov',
        placeOfBirth: 'Pleven',
        role: 'Invigilator',
        avatar: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCmqwK12ceGCMEznj4TosNM7RSzZRAfebyMA&usqp=CAU',
    },
    {
        userId: userId[3],
        dateOfBirth: '1990-03-08',
        email: 'mi@abv.bg',
        fullName: 'Mimi Mimina',
        placeOfBirth: 'Svoge',
        role: 'Examiner',
        avatar: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcqHu9a_tdZwG-2CIlRyZe321fDNnqi3K0jQ&usqp=CAU',
    },
];

exports.roles = () => [
    {
        role: 'User',
        question: { create: false, del: false },
        exam: { create: false, del: false },
        configuration: { create: false, del: false },
        settings: { edit: false },
    },
    {
        role: 'Examiner',
        question: { create: true, del: true },
        exam: { create: true, del: true },
        configuration: { create: true, del: true },
        settings: { edit: false },
    },
    {
        role: 'Instructor',
        question: { create: true, del: false },
        exam: { create: false, del: false },
        configuration: { create: true, del: true },
        settings: { edit: false },
    },
    {
        role: 'Invigilator',
        question: { create: false, del: false },
        exam: { create: true, del: false },
        configuration: { create: true, del: false },
        settings: { edit: false },
    },
    {
        role: 'Admin',
        question: { create: true, del: true },
        exam: { create: true, del: true },
        configuration: { create: true, del: true },
        settings: { edit: true },
    },
];
